name: Snyk SAST Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  snyk-sast:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Code (SAST)
        run: snyk code test --sarif-file-output=snyk-sast.sarif
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload SAST results
        if: ${{ always() }}
        run: |
          if [ -f snyk-sast.sarif ]; then
            echo "Uploading SARIF..."
            gh api repos/${{ github.repository }}/code-scanning/sarifs \
              -f sarif=@snyk-sast.sarif \
              -F commit_sha=${{ github.sha }} \
              -F ref=${{ github.ref }} \
              -H "Accept: application/vnd.github+json"
          else
            echo "No SAST SARIF to upload"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
