name: Snyk SAST Scan with Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  snyk-sast:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 🔹 Run Snyk Code (SAST) and create SARIF + HTML report
      - name: Run Snyk Code (SAST)
        run: |
          # SARIF faylı GitHub Security tab üçün
          snyk code test --sarif-file-output=snyk-sast.sarif
          
          # HTML report çıxartmaq üçün
          snyk code test --json > snyk-sast.json
          snyk-to-html -i snyk-sast.json -o snyk-sast-report.html
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 🔹 Upload SAST SARIF to Security tab
      - name: Upload SAST SARIF
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-sast.sarif

      # 🔹 Upload HTML report as artifact
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: snyk-sast-report
          path: snyk-sast-report.html
