name: Snyk Scan

on:
  workflow_dispatch:

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Snyk to check for vulnerabilities
        id: snyk
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test --all-projects --sarif-file-output=snyk-report.sarif

      # Əgər fayl yoxdursa boş fayl yarat
      - name: Ensure SARIF exists
        run: |
          if [ ! -f snyk-report.sarif ]; then
            echo "{}" > snyk-report.sarif
          fi

      - name: Upload Snyk report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.sarif
